### ISSUE TITLE
worker goes into error after CP departed

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/k8s-operator#75]
### Bug Description

after https://github.com/canonical/k8s-operator/issues/74 

I just `juju remove-application k8s` and got error state on both workers

```
maksim@darmbeliaev:~$ juju status
Model          Controller              Cloud/Region         Version  SLA          Timestamp
canonical-k8s  k8s-machines-contoller  localhost/localhost  3.4.2    unsupported  17:15:17+02:00

App         Version  Status  Scale  Charm       Channel      Rev  Exposed  Message
k8s-worker  1.30.0   error       2  k8s-worker  latest/edge   34  no       hook failed: "cluster-relation-departed"

Unit           Workload  Agent  Machine  Public address  Ports  Message
k8s-worker/0   error     idle   1        10.112.13.21           hook failed: "cluster-relation-departed"
k8s-worker/1*  error     idle   2        10.112.13.10           hook failed: "cluster-relation-departed"

Machine  State    Address       Inst id              Base          AZ  Message
1        started  10.112.13.21  manual:10.112.13.21  ubuntu@22.04      Manually provisioned machine
2        started  10.112.13.10  manual:10.112.13.10  ubuntu@22.04      Manually provisioned machine
4        started  10.112.13.54  manual:10.112.13.54  ubuntu@22.04      Manually provisioned machine

```

### Relevant log output

```shell
unit-k8s-worker-1: 17:12:59 ERROR unit.k8s-worker/1.juju-log cluster:2: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 3022, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-k8s-worker-1/relation-get', '-r', '2', '-', 'k8s-worker/1', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/./k8s/src/charm.py", line 596, in <module>
    ops.main.main(K8sCharm)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/framework.py", line 352, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/framework.py", line 851, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/framework.py", line 941, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/charms/reconciler.py", line 35, in reconcile
    self.reconcile_function(event)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/./k8s/src/charm.py", line 477, in _reconcile
    self._join_cluster()
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/./k8s/src/charm.py", line 439, in _join_cluster
    if self.collector.joined(relation):
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/k8s/src/token_distributor.py", line 72, in joined
    data = relation.data[self.charm.unit].get("joined")
  File "/usr/lib/python3.10/_collections_abc.py", line 824, in get
    return self[key]
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 1705, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 806, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 790, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 1589, in _load
    return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 3095, in relation_get
    raw_data_content = self._run(*args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 3024, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied

unit-k8s-worker-1: 17:12:59 ERROR juju.worker.uniter.operation hook "cluster-relation-departed" (via hook dispatching script: dispatch) failed: exit status 1
unit-k8s-worker-1: 17:12:59 INFO juju.worker.uniter awaiting error resolution for "relation-departed" hook
unit-k8s-worker-1: 17:13:09 INFO juju.worker.uniter awaiting error resolution for "relation-departed" hook
unit-k8s-worker-1: 17:13:09 INFO unit.k8s-worker/1.juju-log cluster:2: Applying Proxied Environment Settings
unit-k8s-worker-1: 17:13:09 INFO unit.k8s-worker/1.juju-log cluster:2: Ensuring k8s snap version
unit-k8s-worker-1: 17:13:10 WARNING unit.k8s-worker/1.cluster-relation-departed snap "k8s" has no updates available
unit-k8s-worker-1: 17:13:10 INFO unit.k8s-worker/1.juju-log cluster:2: Applying K8s requirements
unit-k8s-worker-1: 17:13:10 INFO unit.k8s-worker/1.juju-log cluster:2: Check if k8ds is ready
unit-k8s-worker-1: 17:13:10 INFO unit.k8s-worker/1.juju-log cluster:2: Status context closed with: []
unit-k8s-worker-1: 17:13:10 ERROR unit.k8s-worker/1.juju-log cluster:2: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 3022, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-k8s-worker-1/relation-get', '-r', '2', '-', 'k8s-worker/1', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/./k8s/src/charm.py", line 596, in <module>
    ops.main.main(K8sCharm)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/framework.py", line 352, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/framework.py", line 851, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/framework.py", line 941, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/charms/reconciler.py", line 35, in reconcile
    self.reconcile_function(event)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/./k8s/src/charm.py", line 477, in _reconcile
    self._join_cluster()
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/./k8s/src/charm.py", line 439, in _join_cluster
    if self.collector.joined(relation):
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/k8s/src/token_distributor.py", line 72, in joined
    data = relation.data[self.charm.unit].get("joined")
  File "/usr/lib/python3.10/_collections_abc.py", line 824, in get
    return self[key]
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 1705, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 806, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 790, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 1589, in _load
    return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 3095, in relation_get
    raw_data_content = self._run(*args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-k8s-worker-1/charm/venv/ops/model.py", line 3024, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied
```

**Comment by eaudetcobello** [comment]
See https://github.com/canonical/k8s-operator/issues/74
