### ISSUE TITLE
K8s Leader fails to remove node

### ISSUE THREAD

**Issue by addyess** [canonical/k8s-operator#85]
### Bug Description

In CI, i found a k8s unit whose unit was gone, but had not been removed from the cluster.  

Upon further investigation, it seems that the unit was never placed in the k8s cluster relation databag. 
When the node-name is not in this mapping, the cluster leader doesn't know it should be removed by the token_distributor. 

### To Reproduce

```bash
juju deploy k8s -n 3
# wait for stable
juju remove-unit k8s/2
```

### Environment

GH CI

### Relevant log output

```shell
This is the most relevant log from the k8s leader.  You'll noticed the departed relation hook for k8s/2 -- but there's no mention of "Completed Token allocation of ..." for k8s/2


2024-04-26 11:12:10 DEBUG juju.worker.uniter.operation executor.go:85 running operation run relation-departed (0; unit: k8s/2, departee: k8s/2) hook for k8s/1
2024-04-26 11:12:10 DEBUG juju.worker.uniter.operation executor.go:88 acquiring machine lock for k8s/1
2024-04-26 11:12:10 DEBUG juju.machinelock machinelock.go:166 acquire machine lock "machine-lock" for k8s/1 uniter (run relation-departed (0; unit: k8s/2, departee: k8s/2) hook)
2024-04-26 11:12:10 DEBUG juju.machinelock machinelock.go:176 machine lock "machine-lock" acquired for k8s/1 uniter (run relation-departed (0; unit: k8s/2, departee: k8s/2) hook)
2024-04-26 11:12:10 DEBUG juju.worker.uniter.operation executor.go:135 preparing operation "run relation-departed (0; unit: k8s/2, departee: k8s/2) hook" for k8s/1
2024-04-26 11:12:10 DEBUG juju.worker.uniter.operation executor.go:135 executing operation "run relation-departed (0; unit: k8s/2, departee: k8s/2) hook" for k8s/1
2024-04-26 11:12:10 DEBUG juju.worker.uniter agent.go:22 [AGENT-STATUS] executing: running cluster-relation-departed hook for k8s/2
2024-04-26 11:12:10 DEBUG juju.worker.uniter.runner runner.go:719 starting jujuc server  {unix @/var/lib/juju/agents/unit-k8s-1/agent.socket <nil>}
2024-04-26 11:12:10 DEBUG unit.k8s/1.juju-log server.go:325 cluster:0: ops 2.12.0 up and running.
2024-04-26 11:12:10 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Determined this cloud provider is QEMU

2024-04-26 11:12:10 WARNING unit.k8s/1.juju-log server.go:325 cluster:0: Failed to identify cloud from machine's vendor: QEMU

2024-04-26 11:12:10 DEBUG unit.k8s/1.juju-log server.go:325 cluster:0: Emitting Juju event cluster_relation_departed.
2024-04-26 11:12:10 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Reconcile event=<RelationDepartedEvent via K8sCharm/on/cluster_relation_departed[166]>
2024-04-26 11:12:10 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Applying Proxied Environment Settings
2024-04-26 11:12:10 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Ensuring k8s snap version
2024-04-26 11:12:10 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Refreshing snap k8s, revision None, tracking edge
2024-04-26 11:12:11 WARNING unit.k8s/1.cluster-relation-departed logger.go:60 snap "k8s" has no updates available
2024-04-26 11:12:11 INFO unit.k8s/1.juju-log server.go:325 cluster:0: The snap installation completed successfully
2024-04-26 11:12:11 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Applying K8s requirements
2024-04-26 11:12:11 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Check if k8ds is ready
2024-04-26 11:12:11 INFO unit.k8s/1.juju-log server.go:325 cluster:0: K8s cluster already bootstrapped
2024-04-26 11:12:11 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Enabling K8s features
2024-04-26 11:12:18 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Prepare clustering
2024-04-26 11:12:18 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Completed token allocation of control-plane unit=cluster:k8s/1
2024-04-26 11:12:18 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Completed token allocation of control-plane unit=cluster:k8s/0
2024-04-26 11:12:18 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Completed token allocation of worker unit=k8s-cluster:k8s-worker/1
2024-04-26 11:12:18 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Completed token allocation of worker unit=k8s-cluster:k8s-worker/2
```

### Additional context

We also should clean up the tokens in juju once they've been used/revoked

**Comment by addyess** [comment]
More details, I think what's happening is that a node fails half-way to join.  It REALLY ends up joining, but times out waiting on the snap to respond in.  The next reconcile loop, it finds itself bootstrapped -- but never sets the "joined" value in the relation data.

```
2024-04-26 15:49:20 INFO unit.k8s/1.juju-log server.go:325 cluster:0: Joining juju-43c064-3 to 10.183.171.199:6400...
2024-04-26 15:49:50 DEBUG unit.k8s/1.juju-log server.go:325 cluster:0: Found expected exception: Error status 500
	method=POST
	endpoint=/1.0/k8sd/cluster/join
	reason=Internal Server Error
	body={"type":"error","status":"","status_code":0,"operation":"","error_code":500,"error":"failed to join k8sd cluster as control plane: Post \"http://control.socket/cluster/control\": context deadline exceeded","metadata":null}


2024-04-26 15:49:50 ERROR unit.k8s/1.juju-log server.go:325 cluster:0: Caught ReconcilerError
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-k8s-1/charm/venv/charms/contextual_status.py", line 101, in on_error
    yield
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "./src/charm.py", line 556, in _join_cluster
    self.api_manager.join_cluster(request)
  File "/var/lib/juju/agents/unit-k8s-1/charm/lib/charms/k8s/v0/k8sd_api_manager.py", line 695, in join_cluster
    self._send_request(endpoint, "POST", EmptyResponse, request)
  File "/var/lib/juju/agents/unit-k8s-1/charm/lib/charms/k8s/v0/k8sd_api_manager.py", line 651, in _send_request
    raise InvalidResponseError(
charms.k8s.v0.k8sd_api_manager.InvalidResponseError: Error status 500
	method=POST
	endpoint=/1.0/k8sd/cluster/join
	reason=Internal Server Error
	body={"type":"error","status":"","status_code":0,"operation":"","error_code":500,"error":"failed to join k8sd cluster as control plane: Post \"http://control.socket/cluster/control\": context deadline exceeded","metadata":null}



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-k8s-1/charm/venv/charms/reconciler.py", line 35, in reconcile
    self.reconcile_function(event)
  File "./src/charm.py", line 587, in _reconcile
    self._join_cluster()
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/var/lib/juju/agents/unit-k8s-1/charm/venv/charms/contextual_status.py", line 106, in on_error
    raise ReconcilerError(msg) from e
charms.contextual_status.ReconcilerError: Found expected exception: Error status 500
	method=POST
	endpoint=/1.0/k8sd/cluster/join
	reason=Internal Server Error
	body={"type":"error","status":"","status_code":0,"operation":"","error_code":500,"error":"failed to join k8sd cluster as control plane: Post \"http://control.socket/cluster/control\": context deadline exceeded","metadata":null}


```
